= Dictionaries

Public API and types for internal Shen dictionary data structure.

== API

=== Construction

==== `dict.make` : `number --> (dict.t K V)`

`(dict.make SizeHint)` creates a new dictionary. `SizeHint` must be a positive
integer and is a size hint for the underlying implementation. The recommended value is
the expected number of values this dictionary will hold, or `1` if no values are expected.

=== Predicates

==== `dict.is?` : `A --> boolean`

`(dict.is? X)` returns `true` if `X` is a dictionary, and `false` otherwise.

=== Access

==== `dict.get` : `(dict.t K V) --> K --> V`

`(dict.get Dict Key)` returns the value in `Dict` associated with `Key`.
Raises an error if no value associated with `Key` is found.

=== Modification

==== `dict.set` : `(dict.t K V) --> K --> V --> V`

`(dict.set Dict Key Value)` associates `Value` with `Key` in `Dict` and returns
`Value`.

==== `dict.delete` : `(dict.t K V) --> K --> K`

`(dict.delete Dict Key)` deletes the value associated with `Key` in `Dict` and
returns `Key`. If `Key` is absent, the dictionary is unchanged and `Key` is
still returned.

=== Traversal

==== `dict.fold` : `(K --> V --> A --> A) --> (dict.t K V) --> A --> A`

`(dict.fold F Dict Accum)` calls `(F Key Value Accum)` for each association in `Dict`.
The return value of each call to `F` is used as `Accum` in the next call.
Returns the final accumulator, or the initial accumulator if `Dict` is empty.

==== `dict.keys` : `(dict.t K V) --> (list K)`

`(dict.keys Dict)` returns a list of all keys in `Dict`.

==== `dict.values` : `(dict.t K V) --> (list V)`

`(dict.values Dict)` returns a list of all values in `Dict`.

